openapi: 3.0.0
info:
  title: After 3ra pre-entrega
  description: |-
    ### This is an example of API documentation in postman.

    > Run this collection in your local enviromen.
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Carts
    description: '> Requests to test Carts endpoints'
  - name: Products
    description: '> Requests to test the products endpoints.'
  - name: Users
    description: '> Requests to test users endpoints'
paths:
  /api/carts/62c74aa293d4e175b9ad6be5:
    get:
      tags:
        - Carts
      summary: get user cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - _id: 62c85b6b83d7d55b8792ee2d
                  user: 62c74aa293d4e175b9ad6be5
                  carts: []
                  __v: 0
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                error: 'Error getting carts: Cart not found'
    put:
      tags:
        - Carts
      summary: update user cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                carts:
                  - product: 62c7430bd48a322e49b43a58
                    amount: 5
                  - product: 62c7430bd48a322e49b43a59
                    amount: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                _id: 62c85b6b83d7d55b8792ee2d
                user: 62c74aa293d4e175b9ad6be5
                carts:
                  - product: 62c7430bd48a322e49b43a58
                    amount: 5
                  - product: 62c7430bd48a322e49b43a59
                    amount: 10
                __v: 0
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                error: 'Error updating cart: Cart not found'
    delete:
      tags:
        - Carts
      summary: empty user cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                _id: 62c85b6b83d7d55b8792ee2d
                user: 62c74aa293d4e175b9ad6be5
                carts: []
                __v: 0
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                error: 'Error deleting product: Cart not found'
  /api/products/:
    get:
      tags:
        - Products
      summary: get all products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - _id: 62c7430bd48a322e49b43a57
                  name: Oriental Steel Chips
                  description: >-
                    The slim & simple Maple Gaming Keyboard from Dev Byte comes
                    with a sleek body and 7- Color RGB LED Back-lighting for
                    smart functionality
                  code: tu439
                  img: https://loremflickr.com/640/480/technics
                  price: 88586
                  stock: 867
                  __v: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                msg: mocked error response
    post:
      tags:
        - Products
      summary: post a product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: New Steel Chips
                description: >-
                  The slim & simple Maple Gaming Keyboard from Dev Byte comes
                  with a sleek body and 7- Color RGB LED Back-lighting for smart
                  functionality
                code: tu4a9
                img: https://loremflickr.com/640/480/technics
                price: 999
                stock: 333
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                msg: 'Adding product: '
                data:
                  name: New Steel Chips
                  description: >-
                    The slim & simple Maple Gaming Keyboard from Dev Byte comes
                    with a sleek body and 7- Color RGB LED Back-lighting for
                    smart functionality
                  code: tu4a9
                  img: https://loremflickr.com/640/480/technics
                  price: 999
                  stock: 333
                  _id: 62c79061104673accf6457c3
                  __v: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                msg: >-
                  Falta ingresar alguno de los campos obligatorios o está en un
                  formato incorrecto: Name, Code, Price y Stock
  /api/products/wrongproduct:
    get:
      tags:
        - Products
      summary: get a single product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                _id: 62c7430bd48a322e49b43a57
                name: Oriental Steel Chips
                description: >-
                  The slim & simple Maple Gaming Keyboard from Dev Byte comes
                  with a sleek body and 7- Color RGB LED Back-lighting for smart
                  functionality
                code: tu439
                img: https://loremflickr.com/640/480/technics
                price: 88586
                stock: 867
                __v: 0
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                msg: >-
                  Error getting product: Cast to ObjectId failed for value
                  "62c7430bd48a322e49b43a" (type string) at path "_id" for model
                  "products"
  /api/products/62c7430bd48a322e49b43a58:
    put:
      tags:
        - Products
      summary: update a product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: John Lennon Album
                description: This is a description
                code: 3x3x3x
                img: https://loremflickr.com/640/480/technics
                price: 888
                stock: 111
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                msg: Updating Product
                data:
                  _id: 62c7430bd48a322e49b43a58
                  name: John Lennon Album
                  description: This is a description
                  code: 3x3x3x
                  img: https://loremflickr.com/640/480/technics
                  price: 888
                  stock: 111
                  __v: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                msg: >-
                  Falta ingresar alguno de los campos obligatorios o está en un
                  formato incorrecto: Name, Code, Price y Stock
  /api/auth/signup:
    post:
      tags:
        - Users
      summary: user signup
      description: Signup new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Pepe
                lastName: Perez
                email: pepeperez@coder.com
                age: 48
                isAdmin: false
                password: password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                msg: signup successful
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
              example: Bad Request
  /api/auth/login:
    get:
      tags:
        - Users
      summary: user login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                msg: login successful
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              example: Unauthorized
