openapi: 3.0.0
info:
  title: After 3ra pre-entrega
  description: |-
    ### This is an example of API documentation in postman.

    > Run this collection in your local enviromen.
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Products
    description: Endpoints to test the products database.
paths:
  /api/products/:
    get:
      tags:
        - Products
      summary: Get Products
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Accept-Ranges:
              schema:
                type: string
                example: bytes
            Content-Type:
              schema:
                type: string
                example: text/html; charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '3258'
            ETag:
              schema:
                type: string
                example: W/"cba-NbChDUznGckD3vhBp0A0E/hVjBo"
            Date:
              schema:
                type: string
                example: Thu, 07 Jul 2022 18:56:55 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                msg: mocked response
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Accept-Ranges:
              schema:
                type: string
                example: bytes
            Content-Type:
              schema:
                type: string
                example: text/html; charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '3258'
            ETag:
              schema:
                type: string
                example: W/"cba-NbChDUznGckD3vhBp0A0E/hVjBo"
            Date:
              schema:
                type: string
                example: Thu, 07 Jul 2022 18:56:55 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                msg: mocked error response